### ISSUE TITLE
BigTiff support

### ISSUE THREAD

**Issue by jayvdb** [kornelski/rexif#5]
Is this project interested in BigTiff being added?  c.f. https://github.com/gufo-rs/gufo/issues/1

It looks like this project isnt exposing the IDF offsets in the public interface, so probably wont have a significant breakage to support BigTiff , however pubs enums like  `IfdFormat` and `TagValue` will need to be expanded.

**Comment by kornelski** [comment]
Yes, I'd be interested in supporting it. Would you make a PR?

**Comment by jayvdb** [comment]
No. I was expecting https://github.com/kornelski/rexif/pull/4 to get merged.  I have a policy of not contributing to projects that dont use clippy and rustfmt.

**Comment by kornelski** [comment]
That's fine by me.
